// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Login.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ClientType);
GPB_ENUM_FWD_DECLARE(ResultType);
GPB_ENUM_FWD_DECLARE(UserStatType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImLoginRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ImLoginRoot : GPBRootObject
@end

#pragma mark - IMLoginReq

typedef GPB_ENUM(IMLoginReq_FieldNumber) {
  IMLoginReq_FieldNumber_UserId = 1,
  IMLoginReq_FieldNumber_Passwd = 2,
  IMLoginReq_FieldNumber_OnlineStatus = 3,
  IMLoginReq_FieldNumber_ClientType = 4,
  IMLoginReq_FieldNumber_DeviceId = 5,
  IMLoginReq_FieldNumber_ClientVersion = 6,
  IMLoginReq_FieldNumber_Token = 7,
};

@interface IMLoginReq : GPBMessage

///cmd id:		0x0103
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwd;

@property(nonatomic, readwrite) enum UserStatType onlineStatus;

@property(nonatomic, readwrite) enum ClientType clientType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

/// Fetches the raw value of a @c IMLoginReq's @c onlineStatus property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t IMLoginReq_OnlineStatus_RawValue(IMLoginReq *message);
/// Sets the raw value of an @c IMLoginReq's @c onlineStatus property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetIMLoginReq_OnlineStatus_RawValue(IMLoginReq *message, int32_t value);

/// Fetches the raw value of a @c IMLoginReq's @c clientType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t IMLoginReq_ClientType_RawValue(IMLoginReq *message);
/// Sets the raw value of an @c IMLoginReq's @c clientType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetIMLoginReq_ClientType_RawValue(IMLoginReq *message, int32_t value);

#pragma mark - IMLoginRes

typedef GPB_ENUM(IMLoginRes_FieldNumber) {
  IMLoginRes_FieldNumber_ServerTime = 1,
  IMLoginRes_FieldNumber_ErrCode = 2,
  IMLoginRes_FieldNumber_ErrMsg = 3,
  IMLoginRes_FieldNumber_OnlineStatus = 4,
};

@interface IMLoginRes : GPBMessage

///cmd id:		0x0104
@property(nonatomic, readwrite) uint32_t serverTime;

@property(nonatomic, readwrite) enum ResultType errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite) enum UserStatType onlineStatus;

@end

/// Fetches the raw value of a @c IMLoginRes's @c errCode property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t IMLoginRes_ErrCode_RawValue(IMLoginRes *message);
/// Sets the raw value of an @c IMLoginRes's @c errCode property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetIMLoginRes_ErrCode_RawValue(IMLoginRes *message, int32_t value);

/// Fetches the raw value of a @c IMLoginRes's @c onlineStatus property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t IMLoginRes_OnlineStatus_RawValue(IMLoginRes *message);
/// Sets the raw value of an @c IMLoginRes's @c onlineStatus property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetIMLoginRes_OnlineStatus_RawValue(IMLoginRes *message, int32_t value);

#pragma mark - IMLogoutReq

///cmd id:		0x0105
@interface IMLogoutReq : GPBMessage

@end

#pragma mark - IMLogoutRsp

typedef GPB_ENUM(IMLogoutRsp_FieldNumber) {
  IMLogoutRsp_FieldNumber_ErrCode = 1,
};

@interface IMLogoutRsp : GPBMessage

///cmd id:		0x0106
@property(nonatomic, readwrite) uint32_t errCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
